### ISSUE TITLE
Errors with some url basemaps

### ISSUE THREAD

**Issue by Xatpy** [CartoDB/CartoDB-basemaps#10]
I had some errors while I was zooming (quickly) in a basemap.
The URLs are:
```
http://2.basemaps.cartocdn.com/light_all/18/162991/208806.png
http://3.basemaps.cartocdn.com/light_all/18/162991/208807.png
http://1.basemaps.cartocdn.com/light_all/18/162990/208806.png
http://2.basemaps.cartocdn.com/light_all/18/162990/208807.png
http://4.basemaps.cartocdn.com/light_all/18/162992/208807.png
http://4.basemaps.cartocdn.com/light_all/18/162989/208806.png
http://4.basemaps.cartocdn.com/light_all/18/162993/208806.png
http://1.basemaps.cartocdn.com/light_all/18/162989/208807.png
```

![screen shot 2015-01-27 at 12 38 06](https://cloud.githubusercontent.com/assets/3958416/5917788/80f485ac-a621-11e4-8efe-8423a5cffdb1.png)

@rochoa told me about opening this ticket.

**Comment by rochoa** [comment]
There was an issue with the associated named maps, it should be fixed now. Check: https://github.com/CartoDB/Windshaft-cartodb/pull/250
