### ISSUE TITLE
Updating the basemaps from OSM

### ISSUE THREAD

**Issue by iriberri** [CartoDB/CartoDB-basemaps#14]
When are the updates expected? I also remember that @andrewxhill said a couple of days ago that our NYC office building was not the one in the easter egg. :smile: 

We've been asked about this in Support SB/4663504.

cc @javisantana @saleiva @zenitraM

**Comment by dbauszus** [comment]
Are there any news in regard to a basemap update? Is it planned to run an annual update? There are still a few problems in the UK with double place names and shifted buildings in the central London area.

**Comment by zenitraM** [comment]
We are working on it, expect them to be updated soon!
