### ISSUE TITLE
Tasman peninsula doesn't appear on zooms > 9

### ISSUE THREAD

**Issue by iriberri** [CartoDB/CartoDB-basemaps#16]
When you zoom, this region disappears

![image](https://cloud.githubusercontent.com/assets/1730320/6527978/5b3dfe12-c41f-11e4-9c2b-02e321908704.png)

![image](https://cloud.githubusercontent.com/assets/1730320/6527987/61b088a0-c41f-11e4-9b0c-cd7bc18ece8e.png)

![image](https://cloud.githubusercontent.com/assets/1730320/6527994/68da0e80-c41f-11e4-8f2d-5043fda8aadc.png)

Reported in support in SB/4713659

cc @andrewxhill @zenitraM @javisantana @saleiva

**Comment by mojodna** [comment]
Pulling updated land polygons from http://openstreetmapdata.com/data/land-polygons might help (though they might also come with some regressions--we were missing Lake Ontario for a while).
