### ISSUE TITLE
Wrong name in Positron cartoDB

### ISSUE THREAD

**Issue by fabwoj** [CartoDB/CartoDB-basemaps#20]
Hi, 
While displaying a Positron map from cartoDB, I noticed a mistake about a name (CAYENNE) which is bigger than it should be.
![cayennepositron](https://cloud.githubusercontent.com/assets/12254720/7474367/34c49678-f341-11e4-954d-a5d332affe31.PNG)
CAYENNE is only a street name, there is no city called CAYENNE in this area (Normandy, France).
Thanks.

**Comment by almccon** [comment]
That city is originally sourced from geonames: http://www.geonames.org/3028097/cayenne.html

The population in geonames is 58 492, but I think this is incorrect. That's the correct population for Cayenne, French Guyana, and I think someone incorrectly add this population to the village in northern France.

I removed the population for that feature in geonames, but I don't have enough local knowledge to delete it completely. Maybe there is a historic village there?

I will also completely remove this Cayenne from the source file used for labeling in the CartoDB basemaps.

**Comment by fabwoj** [comment]
Hi Alan,
No historic village there. I live 10 km from this place. My parents live in Ménerval. I know this area. Cayenne is not a village. On google maps, 
you can see , in this area,  a little road called Cayenne. Cayenne is also a brook. 

Thanks for your help.
Fabrice

**Comment by almccon** [comment]
Okay, I deleted that Cayenne entirely from geonames.

**Comment by fabwoj** [comment]
Thank you Alan !
Could you tell me when Cayenne will disappear on Positron map ?
Best,
Fabrice

**Comment by almccon** [comment]
That's a question for the CartoDB crew. It depends on when they push the change to their renderers. @javisantana?
