### ISSUE TITLE
Duplicated labels in UK

### ISSUE THREAD

**Issue by iriberri** [CartoDB/CartoDB-basemaps#23]
![image](https://cloud.githubusercontent.com/assets/1730320/7676770/0f22dd98-fd47-11e4-95ce-fdd537b5f078.png)

![image](https://cloud.githubusercontent.com/assets/1730320/7676772/11f66e9a-fd47-11e4-8557-f7c23c8559ce.png)

From SB/5364368

ping @zenitraM

**Comment by mojodna** [comment]
I suspect that this has to do with using `place=*` polygons **and** nodes, something which we've tried to deal with in the past.  Mapnik 3 adds `text-repeat-distance` (CSS name) that's similar to `text-min-distance`, but works for things other than lines (and is supposedly keyed off the text itself, not the underlying feature).

**Comment by pnorman** [comment]
wfm on develop.. It feels metatile related, but it's hard to be sure.
