### ISSUE TITLE
Clipped city labels at zoom 7

### ISSUE THREAD

**Issue by almccon** [CartoDB/CartoDB-basemaps#33]
All happening along tile boundaries:

![screen shot 2015-10-20 at 2 53 13 pm](https://cloud.githubusercontent.com/assets/1212178/10622171/8132ccaa-773a-11e5-93a5-db47b023bd03.png)

![screen shot 2015-10-20 at 2 53 01 pm](https://cloud.githubusercontent.com/assets/1212178/10622172/81333078-773a-11e5-9c3a-4a9ddbe4567f.png)

**Comment by pnorman** [comment]
Seems to be fixed with the new work (#59)
