### ISSUE TITLE
Customize CartoDB positron 

### ISSUE THREAD

**Issue by thucnc** [CartoDB/CartoDB-basemaps#34]
I want to show labels of district and ward in the map and hide other labels but dont know how to do it. (I tried update the style in cartdb css editor as below but it does not work). Please help, sorry if this question is out of scope on this repo. (i used text-opacity = 0 to hide all existing labels)
```
#osmroads_labels [kind='major_road'] {
  text-name: "[name]";
  text-opacity: 0;
  text-placement: line;
  text-face-name: "Azo Sans Regular","DejaVu Sans Bold","unifont Medium";
  text-fill: @osm_roads_labels_fill;
  text-transform: uppercase;
  text-halo-radius: 1.8;
  text-halo-fill: @osm_roads_labels_halo;
  text-size: 10px;
  text-character-spacing: 1.0;
  text-max-char-angle-delta: 30;
  text-min-distance: 14;
  text-avoid-edges: true;
  text-dy: 5;

  [zoom>=13] {
    text-size: 10px;
  }
}
```

**Comment by almccon** [comment]
Hi. This repo is for the stylesheet that is used to generate the CartoDB basemaps, but the basemaps are not customizable by the average user. To generate basemaps yourself, you would need to have a copy of the entire OSM planet file in your CartoDB account, which is several gigabytes of data.

Only CartoDB employees are able to modify these styles to change the CartoDB basemaps. Sorry.

**Comment by pnorman** [comment]
To expand on this, these styles are designed to make use of existing CartoDB infrastructure like sync tables, the SQL api, the tilers, our CDN, and other components. The style could be adapted to be used without these components, but this would require some effort, and I'm not sure this style would be a good starting point for a different project.

For your specific use case, you could use the unlabeled style and add your own district and ward labels as an overlay.
