### ISSUE TITLE
Outdated label for Barbate (Cádiz)

### ISSUE THREAD

**Issue by ernesmb** [CartoDB/CartoDB-basemaps#36]
The label for Barbate (Cádiz) in Positron, Dark Matter and Stamen basemaps shows an incorrect and outdated name: 'Barbate de Franco'. 
Apparently that name was changed to just 'Barbate' in 1981.
The outdated label only appears in zoom levels 9-12. 
## Steps to reproduce
- Open a CartoDB map
- Go to Barbate (36.183333, -5.916667)
- Zoom to a level between 9 and 12
- See outdated label
- Zoom in to a >12 level. Updated label appears

**Comment by almccon** [comment]
Fixed in https://github.com/stamen/aries-magic-list/commit/b6658f170d7aa4b61adcd709b77a1b45fd6f0e69, and will be fixed on the map next time you reload the data.
