### ISSUE TITLE
Fictional Location in Manchester labeled

### ISSUE THREAD

**Issue by ernesmb** [CartoDB/CartoDB-basemaps#37]
There is a label for a fictional location in Manchester in Positron and Dark Matter basemaps. 
The name of the place is Weatherfield, and according to the person who reported it: 

> Weatherfield is not a real place, it is the location of the TV soap opera Coronation Street. The studios which produce the show are located where the name Weatherfield appears.

These are the approximate Lat/Lon coordinates of the place: 53.4697012,-2.3069207

![captura de pantalla 2015-12-22 a las 11 39 21](https://cloud.githubusercontent.com/assets/10940006/11953472/c1d6611c-a8a0-11e5-8a7b-9b3f0996b848.png)

**Comment by almccon** [comment]
That name comes from the OpenStreetMap source data. Here is the `neighbourhood` feature in question: http://www.openstreetmap.org/way/300720995

It looks like the default OpenStreetMap rendering doesn't show the label (because it prioritizes other features instead of neighborhoods).
