### ISSUE TITLE
Positron(labels below) & Dark Matter labels are cut off at tile edges in Firefox & Chrome

### ISSUE THREAD

**Issue by ztephm** [CartoDB/CartoDB-basemaps#38]
* moved from https://github.com/CartoDB/cartodb/issues/6225#issuecomment-166245864

@xavijam cc @zenitraM 

S/B 7574208

## Context
These basemaps have "Indian Ocean" and/or "South Atlantic Ocean" labels cut off at tile edges @zoom level 2: 
[in Chrome 47.0.2526.73 and Firefox 42.0]

* Dark Matter
* Positron (labels below)

## Process
1. Open any map in CartoDB Editor
2. Zoom to level 2
3. Change basemap > Positron(labels below)
4. Change basemap > Dark Matter

## Expected result
Labels won't be cut off at tile edges

## Current result
![chrome_positronbelow](https://cloud.githubusercontent.com/assets/1779444/11669240/b5bfd5e8-9dc9-11e5-954a-5cfe35b6055c.png)

![chrome_darkmatter](https://cloud.githubusercontent.com/assets/1779444/11669243/bab9d30a-9dc9-11e5-8b32-df0cd9142f4e.png)

Maybe CartoCSS buffer has to be increased?

* related? https://github.com/CartoDB/CartoDB-basemaps/issues/33

**Comment by almccon** [comment]
Hmm, it's happening in both versions of Positron (labels below, and labels above), but in Dark Matter it's only happening with labels above. Dark Matter with labels below works fine.

![screen shot 2016-01-06 at 5 45 53 pm](https://cloud.githubusercontent.com/assets/1212178/12160095/5fbfd400-b49d-11e5-990b-b0765803fee1.png)

So, I suggest we see what Dark Matter With Labels Below is doing, and replicate that across the other styles.

**Comment by pnorman** [comment]
Seems to be fixed with the new work (#59)
