### ISSUE TITLE
Neighborhoods missing in Positron basemap for Durham, NC

### ISSUE THREAD

**Issue by timstallmann** [CartoDB/CartoDB-basemaps#54]
The neighborhoods layer for Positron omits all neighborhoods in South Durham, which also happens to be many of the historically African-American neighborhoods (`West End`, `Hayti`, `Lyon Park`, etc.). I plugged a few of them into OSM about 6 months ago (e.g. https://www.openstreetmap.org/node/3672062438#map=17/35.98581/-78.89872) thinking that the changes would propagate through to Positron but so far they haven't. Any guidance on how to get these to appear? 

It's particularly significant as we're hoping to launch a Durham Civil Rights History map using positron as a basemap sometime in the coming months.

Image is from Durham Neighborhood compass, just as it was the positron map I was looking at most recently.
<img width="507" alt="screen shot 2016-03-08 at 7 00 33 pm" src="https://cloud.githubusercontent.com/assets/6741938/13620760/235a29cc-e560-11e5-935d-5688fab2ab73.png">

Tagging @NeighborhoodCompass as well.

**Comment by almccon** [comment]
Hi @timstallmann and @neighborhoodcompass!

The CartoDB basemaps are using an older snapshot of the OSM database, which probably predates the time you added those neighborhood points. @pnorman has been working on the basemaps more recently, and he might know more about the timeline for refreshing the database.

One workaround would be to add your own label layer, or even just a new layer for the new neighborhood points. You could even use the exact same style that the CartoDB style uses for neighborhood points, so the result will be indistinguishable: https://github.com/CartoDB/CartoDB-basemaps/blob/master/styles/country_city_labels.mss#L77-L129

Sorry for such a hacky solution, but that may be your only option if the basemaps aren't updated before your site launches.

**Comment by timstallmann** [comment]
Ahh thanks @almccon! I was under the impression the data was getting pulled on a regular-ish basis from OSM. That sounds like a reasonable solution in the interim.
