### ISSUE TITLE
Include highway=livingstreet

### ISSUE THREAD

**Issue by zenitraM** [CartoDB/CartoDB-basemaps#56]
There are a lot of those around the center of Madrid that are not in our basemaps:

http://cartodb.github.io/CartoDB-basemaps/preview.html#18/40.42226/-3.70514
http://www.openstreetmap.org/#map=18/40.42226/-3.70514&layers=H
http://www.openstreetmap.org/way/7642906

Maybe we should include them styled as ordinary roads?

**Comment by zenitraM** [comment]
cc @pnorman

**Comment by pnorman** [comment]
Yes - this will require changes to the highroads functions

**Comment by pnorman** [comment]
fixed in #69
