### ISSUE TITLE
Labels not lining across tile borders at zoom level 13

### ISSUE THREAD

**Issue by javitonino** [CartoDB/CartoDB-basemaps#67]
The following image is built by joining two adjacent tiles:
- http://c.basemaps.cartocdn.com/light_only_labels/13/4011/3090.png
- http://c.basemaps.cartocdn.com/light_only_labels/13/4012/3090.png

![two](https://cloud.githubusercontent.com/assets/7569673/14462767/def3c25a-00c8-11e6-8f1b-753d71568104.png)

There are plenty more examples, always at zoom 13. Looking at the headers, they both have the same age, so it does not appear a cache problem.

**Comment by pnorman** [comment]
area is approximately 40.3687/-3.6693

**Comment by pnorman** [comment]
I'm having a hard time reproducing the problems in my development environment, which I expected - cut off label problems tend to be like that.

PR #68 should at the very least help by getting a more consistent ordering of labels across metatiles

**Comment by pnorman** [comment]
Fixed on develop with #68, it'll need a release to production
