### ISSUE TITLE
Broken tiles

### ISSUE THREAD

**Issue by srgpqt** [CartoDB/CartoDB-basemaps#7]
Not sure where to post this, so please excuse me if this is the wrong place.

Some tiles appear to be broken:
http://b.basemaps.cartocdn.com/light_all/12/1243/1434.png

    {"error":"style14: file could not be found: '/home/ubuntu/tile_assets/cache/cfa630a9-capital_shield_light.png'"}

The same tile works in the nolabels variant:

http://b.basemaps.cartocdn.com/light_nolabels/12/1243/1434.png

**Comment by mojodna** [comment]
_tags @zenitraM_

**Comment by zenitraM** [comment]
Hey @srgpqt! Thanks for reporting, we're going to look at it ASAP

*tags @rochoa*
