### ISSUE TITLE
Incorrect Street Names for Barbate in Cadiz, Spain

### ISSUE THREAD

**Issue by michellechandra** [CartoDB/CartoDB-basemaps#74]
35 street names in Barbate have the wrong names. The legal street names should not have the name "Franco" as part of the street name. Update the streets removing any reference to Franco.

[Relevant article](http://www.nerjatoday.com/2008/09/19/street-names-to-change-in-barbate/)

S/B: 9509079

**Comment by almccon** [comment]
I see there are two problems here:

1) the name of the town is "Barbate de Franco" at low zooms (everything up to and include z12). These labels come from https://github.com/stamen/aries-magic-list, and we should fix them there. At zoom 13 and deeper, the name is "Barbate" which is coming from OSM.

<img width="240" alt="screen shot 2016-07-26 at 26 jul 12 13 09" src="https://cloud.githubusercontent.com/assets/1212178/17151919/6313c324-532a-11e6-835b-8352861b235a.png">

2) The 35 wrong street names. All the street names come from OpenStreetMap, so they need to be fixed there, and then these basemaps will reflect the updated changes whenever the database is updated.

However, I can't find the 35 streets you're referring to, @michellechandra. Can you provide OSM links to screenshots of those roads, either in Positron or in OpenStreetMap itself (if they are still there?)

I see [Avenida del Generalismo](http://www.openstreetmap.org/way/122196897) and I see [Plaza Generalisimo Franco](http://www.openstreetmap.org/way/335895765), but I don't see the 35 street names.

<img width="807" alt="screen shot 2016-07-26 at 26 jul 12 29 43" src="https://cloud.githubusercontent.com/assets/1212178/17152445/aa5905b2-532c-11e6-9d28-ff01be587dfb.png">

**Comment by almccon** [comment]
I updated the place name in Aries Magic List: https://github.com/stamen/aries-magic-list/commit/b6658f170d7aa4b61adcd709b77a1b45fd6f0e69

**Comment by ernesmb** [comment]
related: https://github.com/CartoDB/CartoDB-basemaps/issues/36

**Comment by michellechandra** [comment]
I have asked the user for more information on which streets are incorrect. I will post an update once I hear back from the user. Thanks!

**Comment by ernesmb** [comment]
The user has submitted a list of old/new street names: 

```
OLD NAME, NEW NAME
Avenida del Generalisimo, Avenida de la Mar
Plaza General Franco, Plaza Carlos Cano
Calle General Mola, Calle Mediterráneo
Avenida Jose Antonio, Avenida del Rio Barbate
Calle General Castejón, Calle La Cruz
Calle General Varela, Calle Islas Baleares
Calle Padre Castrillón, Calle Manuel Malia Bernal
Calle Garcia Morato, Calle La Motilla
Calle San Paulino, Calle Jarampa
Calle Almirante Vierna, Calle Luis de Góngora
Calle Once de Marzo, Calle As de Guía
Calle Llano Amarillo, Calle Saladeros
Calle Ramón y Cajal, Calle Palangre
Avenida Ruiz de Alda, Avenida del Faro
Barrio Carrero Blanco, Barrio El Pinar
Calle Jose Martinez Romero, Calle Pablo Picasso
Calle Almirante Estrada, Calle Julio Romero de Torres
Plaza Onésimo Redondo, Plaza del Ronqueo
Calle Manuel Mora de Figueroa, Calle Francisco de Quevedo
Calle General Muñoz Grande, Calle Espinel
Calle Fernández Ladreda, Calle Red a Pie
```

**Comment by almccon** [comment]
Great. Can someone check OpenStreetMap and make sure all of these are fixed? And fix them, if not?

**Comment by ernesmb** [comment]
I have already made those changes. Some elements from the list were wrong, but I tried to update the data according to the actual values from Spanish Cadaster and other cartographic sources.
