### ISSUE TITLE
Incorrect labels at specific location

### ISSUE THREAD

**Issue by ernesmb** [CartoDB/CartoDB-basemaps#80]
A user has reported that there are some streets that are not being correctly labeled, although OSM data has been corrected and those changes already applied to our basemaps. 
# STR
- Open one of our basemaps and navigate to 145.4821, -38.0965 (lon/lat)
- check the image to see the incorrect labeling (image coming from the user): 

![mail_attachment](https://cloud.githubusercontent.com/assets/10940006/18321432/3bc601da-752e-11e6-9d49-650c7f3c7820.gif)

  _South East Boulevard also labelled incorrectly as Mega Rise; Mega Rise also labelled incorrectly as Export Drive_
- [check data in OSM](https://www.openstreetmap.org/edit#map=16/-38.0965/145.4821) to find that street names are correctly placed.

cc/ @CartoDB/support for awareness

**Comment by pnorman** [comment]
Ways in question are https://www.openstreetmap.org/way/340543456/history and https://www.openstreetmap.org/way/340543457, edited about a month ago.

**Comment by coxheab** [comment]
Hi, the base map is still not correct and in line with OSM as edited about 2 months ago.  **Can you please provide a date as to when it will be resolved?**
The west end of South East Boulevard is now incorrectly named Mega Rise, and Mega Rise still has incorrect contradicting labels saying Export Drive.
Regards,
Brett.
