### ISSUE TITLE
Positron label is misspelled compared to OSM version

### ISSUE THREAD

**Issue by ztephm** [CartoDB/CartoDB-basemaps#85]
S/B 11405364

Location:
{"type":"Point","coordinates":[-73.600208,45.5250827]}

### Context
* [Positron shows this neighborhood](https://team.carto.com/u/stephaniemongon/builder/7edf4cbc-f308-11e6-8e3e-0e3ebc282e83/embed) as "Mille-End"

  ![screen shot 2017-02-15 at 10 18 37 am](https://cloud.githubusercontent.com/assets/1779444/22980667/26046f7c-f368-11e6-8880-b634449a4dae.png)

* Client notified us it's supposed to be "Mile End". ["Mile End"](https://www.openstreetmap.org/#map=19/45.52505/-73.60011) is what shows on Open Street Map:

  ![screen shot 2017-02-15 at 10 22 37 am](https://cloud.githubusercontent.com/assets/1779444/22980855/b976cf84-f368-11e6-8dd8-03b7dff6a6fd.png)

* Is there a reason Positron info is different than this OSM version?

**Comment by almccon** [comment]
It looks like that spelling was changed in OSM about four months ago: https://www.openstreetmap.org/node/4342882993/history
So the data for Positron is probably older than that.

![screen shot 2017-02-15 at 15 feb 1 37 10](https://cloud.githubusercontent.com/assets/1212178/22996521/e92cd9f6-f383-11e6-9d50-ebba0f838538.png)
