### ISSUE TITLE
HTTPS CartoDB basemaps

### ISSUE THREAD

**Issue by iriberri** [CartoDB/CartoDB-basemaps#9]
Which is the plan about serving CartoDB basemaps over HTTPS?

**Comment by fguillen** [comment]
We are embedding one of your maps in one of our https pages but we are
having a lot of https warnings.

Also the https icon on the browser shows a disturbing alert.

![screen shot 2015-01-21 at 15 16 55](https://cloud.githubusercontent.com/assets/23043/5840902/1da55026-a199-11e4-8c5b-2142ae16a358.png)

As an example:

- https://daliaresearch.cartodb.com/viz/6d173cee-a092-11e4-b18f-0e018d66dc29/embed_map

![screen shot 2015-01-21 at 15 16 55](https://cloud.githubusercontent.com/assets/23043/5840902/1da55026-a199-11e4-8c5b-2142ae16a358.png)

**Comment by dbauszus** [comment]
var https = 'https://cartodb-basemaps-{s}.global.ssl.fastly.net/{basemap-name}/{z}/{x}/{y}.png'

**Comment by pnorman** [comment]
[https support](https://cartodb.com/basemaps) is now documented, [a tile from it](https://cartodb-basemaps-a.global.ssl.fastly.net/light_all/7/35/46.png) checks out with all chrome reports green, and in a SSL checker cartodb-basemaps-a.global.ssl.fastly.net reports everything is okay, so I'm going to close this.
